version: '2' # specify docker-compose version

# Define the services/containers to be run
services:
  angular: # name of the first service
    ports:
      - "4200:4200" # specify port forewarding
    build: angular-client
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'

  express: #name of the second service
    build: express-server # specify the directory of the Dockerfile
    ports:
      - "3000:3000" #specify ports forewarding
    links:
      - database

  database: # name of the third service
    image: mongo # specify image to build container from
    ports:
      - "27017:27017" # specify port forewarding